# Generated by Django 3.0.7 on 2020-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0002_addroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='addroom',
        ),
    ]
