# Generated by Django 3.0.7 on 2020-06-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0003_auto_20200620_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='username',
            new_name='usernames',
        ),
    ]
