# Generated by Django 3.0.7 on 2020-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0004_auto_20200620_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomid',
            name='user',
            field=models.ManyToManyField(blank=True, to='chatserver.username'),
        ),
    ]
