# Generated by Django 3.0.7 on 2020-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0005_roomid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomid',
            name='user',
        ),
        migrations.AddField(
            model_name='roomid',
            name='userr',
            field=models.ManyToManyField(to='chatserver.username'),
        ),
    ]
