# Generated by Django 3.0.7 on 2020-06-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0006_auto_20200620_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomid',
            name='userr',
        ),
        migrations.CreateModel(
            name='chatid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.TextField(max_length=100)),
                ('chatter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatserver.username')),
                ('roomname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatserver.roomId')),
            ],
        ),
    ]
