# Generated by Django 3.0.7 on 2020-06-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0009_auto_20200620_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatid',
            name='roomname',
        ),
        migrations.AddField(
            model_name='chatid',
            name='roomname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatserver.roomId'),
        ),
    ]
