# Generated by Django 2.2.6 on 2020-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0010_auto_20200620_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatid',
            name='chatroom',
            field=models.CharField(max_length=10000),
        ),
    ]
