# Generated by Django 2.2.6 on 2020-06-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0012_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
