# Generated by Django 2.2.6 on 2020-06-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0014_part'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='part',
            new_name='partt',
        ),
    ]
