# Generated by Django 2.2.6 on 2020-06-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0015_auto_20200623_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partt',
            name='users',
        ),
        migrations.AddField(
            model_name='partt',
            name='chats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatserver.username'),
        ),
    ]
