# Generated by Django 2.2.6 on 2021-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0016_auto_20200623_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(null=True)),
            ],
        ),
    ]
